image: python:3.8
definitions:
  steps:
    - step: &git-sync
        name: git-sync
        script:
          - git checkout cf-shared
          - git pull
          - git remote add sync git@github.com:creativefabrica/express-pipelines.git
          - git fetch sync
          - git push -f sync cf-shared:dev
    - step: &bandit
        name: bandit
        caches:
          - pip
        script:
          - pip install $(cat requirements.txt | grep bandit)
          - bandit -c pyproject.toml -r .
    - step: &pylint
        name: pylint
        caches:
          - pip
        script:
          - pip install $(cat requirements.txt | grep pylint)
          - python pylint.py --modules-file pylint-modules
    - step: &license-check
        name: license-check
        script:
          - pip install --upgrade pip
          - pip install $(cat requirements.txt | grep liccheck)
          - ./run_license_check.sh --modules-file pylint-modules

pipelines:
  branches:
    cf-shared:
      - parallel:
        - step: *git-sync
        - step: *bandit
        - step: *pylint
        - step: *license-check
  default:
    - parallel:
      - step: *bandit
      - step: *pylint
      - step: *license-check
